Add filters and merged into one blade file
andreaselia/filament-laravel-analytics pull request #2
Opened 2022-12-19 09:09 UTC by buzkall

Add filters using a Trait and merge all the blade files into a single one

2022-12-20 19:59 UTC, andreaselia requested changes
Thank you very much for your PR, it is greatly appreciated. I've made a couple of comments around formatting, but the rest looks great. Could you also update your initial PR message with a screenshot of the works (visual) for future reference too, please?

2022-12-20 19:59 UTC, andreaselia commented on src/Widgets/SourcesWidget.php
> +                               ->scopes(['filter' => [$this->filter]])
Indentation fix, something like the below to match the other lines.
```suggestion
                ->scopes(['filter' => [$this->filter]])
```

2022-12-20 19:59 UTC, andreaselia commented on resources/views/widgets/widget.blade.php
> +                            wire:loading.class="animate-pulse"
Could we indent this back a tab, please? Everything should indent 4 spaces, and this looks like 8?

2022-12-22 13:20 UTC, buzkall commented
Done!
I've been doing test on my local installation and I've done another version with just one widget and 4 cards

Something like this:

```
protected function getCards(): array
{
    return [
        Card::make(
            __('Devices'),
            ['items' => PageView::query()
                                ->scopes(['filter' => [$this->filter]])
                                ->select('device as type', DB::raw('count(*) as users'))
                                ->groupBy('type')
                                ->get(),
             'field' => 'type',
             'heading' => [__('Type'), __('Users')],
            ]
        ),

        Card::make(
            __('Users'),
            ['items' => PageView::query()
                                ->scopes(['filter' => [$this->filter]])
                                ->where('device', '!=', 'robot')
                                ->select('country', DB::raw('count(*) as users'))
                                ->groupBy('country')
                                ->get(),
             'field' => 'country',
             'heading' => [__('Country'), __('Users')],
            ]
        ),

        Card::make(
            __('Pages'),
            ['items' => PageView::query()
                                ->scopes(['filter' => [$this->filter]])
                                ->where('device', '!=', 'robot')
                                ->select('uri as page', DB::raw('count(*) as users'))
                                ->groupBy('page')
                                ->get(),
             'field' => 'page',
             'heading' => [__('Page'), __('Users')],
            ]
        ),

        Card::make(
            __('Sources'),
            ['items' => PageView::query()
                                ->scopes(['filter' => [$this->filter]])
                                ->where('device', '!=', 'robot')
                                ->select('source as page', DB::raw('count(*) as users'))
                                ->whereNotNull('source')
                                ->groupBy('source')
                                ->get(),
             'field' => 'page',
             'heading' => [__('Page'), __('Users')],
            ]
        ),
    ];
}
```

with a foreach in the view to get the cards

```
@foreach ($this->getCachedCards() as $card)
```

This way a change in a filter affects the other three but doesn't affect any other filter of another dashboard widget

2022-12-23 19:01 UTC, andreaselia commented
I don't have much knowledge of Filament (still quite new to it), would you recommend we do it that way in the package or keep it as-is?

2022-12-27 13:46 UTC, buzkall commented
I feel it's more clear with just one widget. I've uploaded two new files for you to check it: the widget with the four cards and the view. I've also changed some classes in the view, because when using the dark mode in filament, the data can't be read

2022-12-28 00:37 UTC, merged

2022-12-28 00:38 UTC, andreaselia commented
Thank you for your contribution @buzkall. Hopefully I haven't broken anything from my small code style amendments, but I've merged this in now and pushed a release as v1.1.0.